Footer
fe-aug23-team4/nice-gadgets pull request #5
Opened 2023-12-12 14:18 UTC by mifyy

2023-12-12 15:24 UTC, mifyy commented
https://www.loom.com/share/934e85fe5e1a4391b239cf1fe57ed75b?sid=584000bd-0bdb-450b-8489-7ad589921b73

2023-12-12 15:25 UTC, mifyy commented
I had to hard-code this part because I could not manage to implement it otherwise. Maybe you can offer a better solution

  .footer,
  .footer__dark {
    justify-content: flex-start;
    padding: 32px 0;
    margin: 0;
    flex-direction: column;
    height: 175px;
  }

2023-12-13 09:07 UTC, mpohorenyi requested changes
Good job, please pay attention to the comments. 

You have the wrong @media to phone resolution, look at the layout carefully, there are 320-639

Please rework your styles according to BEM.

2023-12-13 09:07 UTC, mpohorenyi commented on src/modules/shared/components/Footer/Footer.tsx
> +          <Link to="/github" className={`${isDarkTheme ? styles.nav_text__dark : styles.nav_text}`}>
It should redirect to our repository on GitHub.

2023-12-13 09:07 UTC, mpohorenyi commented on src/modules/shared/components/Footer/Footer.tsx
> +          </Link>
It should redirect to the home page `'/'` This is temporary.

2023-12-13 09:07 UTC, mpohorenyi commented on src/modules/shared/components/Footer/Footer.module.scss
> +}
Our project has a mixin for this purpose

2023-12-13 09:07 UTC, mpohorenyi commented on src/modules/shared/components/Footer/Footer.module.scss
> +}
Fonts are already connected to the entire project

2023-12-13 15:19 UTC, mpohorenyi commented on src/modules/shared/components/Footer/Footer.tsx
> +          </Link>
UPD: Need these links to redirect to the "Page in Progress"

2023-12-13 21:02 UTC, merged